image: node:lts

stages:
  - pack

build:
  stage: pack
  cache:
    key: build-cache
    paths:
      - node_modules/
      - lib/
      - .npmrc
    policy: push
  script:
    - echo "//git.lte.e-technik.uni-erlangen.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm ci
    - npm pack